### ISSUE TITLE
Starknopoly - Fully onchain multiplayer strategy game 

### ISSUE THREAD

**Issue by Hujunjob** [BibliothecaDAO/Frontinus-House-Docs#22]
# Frontinus House Builder Proposal

### Introduction
Name or social handle of proposer: LuckyHu
Ethereum Mainnet Address: 0x084E93a9EE840216992ACD2Df0BB7259b9995860
ENS name (optional): hujun.eth
Twitter handle (optional): @jobhu123

### Project Detail
Starknopoly is a total on chain game like the the game Monopoly. [Monopoly](https://www.youtube.com/watch?v=AuWvMgYv03g)
Our team members all like Monopoly very much. We will create a total on chain version that everyone can play it anywhere and anytime. Players can hold their earned assets forever on chain. 
We create the game on Starknet by engine Dojo.
Game Money : $Gold

Players roll the dice and move their roles.

There are three different buildings players can choose to build on land they stand on:
Hotel : Buy and build a hotel by $Gold. When other players stand on your hotel, they should pay hotel fees to you.

Bank : Buy and build a bank by $Gold on land. Bank can accumulate $Gold every block.

Starkbucks : Buy and build a Starkbucks by $Gold on land. Starkbucks can product energy for player. Player roll the dice and walk need to consume energy.

Player can also buy back other players' buildings by spend 130% $Gold of the building price.
This is only the first and simple rules of our beta version. 

In the future, we will create a ultimate monopoly world, where everyone can build many kinds of buildings based on the contracts they use. They can upgrade, trade, destroy buildings and other assets.

### Game Treasury
There is a $Gold treasury in game.There is a 1%~3% tax when players pay hotel fee and buy back fee. The tax will be funded in game treasury. Players can buy $Gold  in treasury by ETH or LORD.  The price is based on the amount of $Gold in treasury. Every player can only buy up to 0.5 ETH totally.
At the end of community competition, all ETH will be refunded to players. 

### Character
Hey I'm LuckyHu, the founder of the Starknopoly game team. I'm also a member of DAO @cryptochasersco, which is one of the biggest web3 DAO school in chinese. I like the Dojo engine, we create a Dojo study group to make it famous in chinese web3 community. We want to create a game based on Dojo we all like to play everyday. Starknopoly is that game. This is the beginning. 
Team members : 
Starknet Contracts : @0xNezha @huaigu 
Game Builder : @Hujunjob 
Frontend : @Hujunjob @Minusbill
PM : @script-money

### Timeline
First version can be played in 2 month.  I estimate a start date of 25/08/2023 and MVP date of 30/10/2023

### Objectives
|  Objective | Contributor | Estimated deadline  |
|  ------- | ------  | ------  |
|  MVP version's contracts based on Dojo | team | 25/10/23  |
|  MVP version's game front end based on phaser | team | 25/10/23  |
|  first community competition | community | 30/10/23  |

### Grant Request
We expect a total cost of 100000 $LORDS.

**Comment by ponderingdemocritus** [comment]
Great idea to bring mechanics on Monopoly onchain!

My feedback:

1. I think there is an opportunity here to use some crypto native math algorithms. You could have a Harbinger Tax on the Land or have hotels/banks on a VRGDA throughout the game. So many possibilities!
2. To me - each round should cost X LORDS, and $GOLD is purely in-game only.

**Comment by Hujunjob** [comment]
> 

Very enlightening opinions. 
We are looking for a good way to upgrade the price of buildings.  
In this first version, the buildings price is affected by amount of single player's buildings and the total amount of whole game. Which is a good game between players and system. 
Harbinger Tax on the Land is a fantastic idea. We will look deeper in it.

**Comment by FlashPhaser** [comment]
Wow, super awesome project! I love playing Monopoly, and as a blockchain player, I am looking forward to the launch of the project. 
Waiting for your good news!

**Comment by Hujunjob** [comment]
> Wow, super awesome project! I love playing Monopoly, and as a blockchain player, I am looking forward to the launch of the project. Waiting for your good news!

Glad to hear that. You will love our game.

**Comment by Fomentador** [comment]
Hey, great to see to the submission. 

Considering monopoly is a turn-based, synchronous multiplayer game where people necessarily need to wait for the other players' turns before it's their turn and they can submit their moves, how exactly do you envision a monopoly game happening on-chain? Does everyone needs to be online at the same time to play a session together or do you plan on introducing some asynchronous gameplay similar to how strategy games do hotseating?

**Comment by Hujunjob** [comment]
> Hey, great to see to the submission.
> 
> Considering monopoly is a turn-based, synchronous multiplayer game where people necessarily need to wait for the other players' turns before it's their turn and they can submit their moves, how exactly do you envision a monopoly game happening on-chain? Does everyone needs to be online at the same time to play a session together or do you plan on introducing some asynchronous gameplay similar to how strategy games do hotseating?

Thanks for your response. 
We upgrade the monopoly to an onchain version. Our game is not turn-based. All players can join and leave anytime. Players just dice and walk. They do not need to wait others.

**Comment by Fomentador** [comment]
So the game would be a single board without limit of players that just runs for some amount of time? This would have some implications. 

The turn mechanic in board games like Monopoly exists to balance the game - in the first few rounds everyone has the same chance of landing on an empty square and buying property, because no one can play 10 turns in a row and just buy up everything. They have to wait for everyone else's turns. If I understand correctly, your proposed version would allow for someone to interact directly with contract at launch (or less efficiently do it manually through the client), going through several game rounds and buying everything they can before anyone else has a turn, and just dominate the game at the start. 

If they cannot buy all properties in every square due to their 0.5 ETH spending limit they'll just buy the most they can, and then have no reason at all to continue to play the game. They can't buy any other property, so playing would just mean paying fees when they land in other players' squares. Continue to play would mean only losing money, so after beginning early and hitting their limit the best move would be to not engage anymore and just rake in other players' fees.

The player limit is also an integral part of Monopoly's design, as unlimited players would result in the same issue listed above: as initial players buy up property in all the squares late players just won't have even the tiniest chance in the game.

Did I misunderstand the design?

**Comment by Hujunjob** [comment]
> 

Thanks for your reply.
1. Players can buy back others' buildings. 0.5E can buy more $Gold if player buy the dip. This is gamble between player and system. 
2. We are considering the Harbinger Tax. It can improve the system economy system.
3. Player can roll the dice once in 10-20 blocks . Can Not roll 10 times at 1 block.
4. The map is much huge than Monopoly. Single player can't buy all buildings at this huge map.
5. Player should balance bank/hotel/farmland.
